[[headers]]
   for = "/*"
   [headers.values]
      cache-control = "public, max-age=600"
      Netlify-CDN-Cache-Control = "public, max-age=600"

[[headers]]
   for = "/(_astro|inter-4.0)/*"
   [headers.values]
      cache-control = "public, max-age=31536000, immutable"
      Netlify-CDN-Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
   for = "/*.{svg,ico}"
   [headers.values]
      cache-control = "public, max-age=6000, immutable"