[[headers]]
   for = "/*.html"
   [headers.values]
      cache-control = "public, max-age=60, stale-while-revalidate=120"
      Netlify-CDN-Cache-Control = "public, max-age=60, stale-while-revalidate=120"

[[headers]]
   for = "*.html"
   [headers.values]
      cache-control = "public, max-age=60, stale-while-revalidate=120"
      Netlify-CDN-Cache-Control = "public, max-age=60, stale-while-revalidate=120"

   
[[headers]]
   for = "/*.svg"
   [headers.values]
      cache-control = "public, max-age=6000, immutable"